version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      # Use target: development when you add multiple stages
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - my-network

# Add this when you have backend
#  backend:
#    build: ./backend
#    ports:
#      - "3000:3000"
#    environment:
#      - NODE_ENV=development
#    networks:
#      - my-network

networks:
  my-network:
    driver: bridge