services:
  frontend:
    build:
      context: ./frontend
      # Use target: development when you add multiple stages
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - my-network

  backend:
    build: ./backend/express-ts-backend

    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - FLASK_BACKEND_URL=http://flask-backend:5000
    networks:
      - my-network

  flask-backend:
    build: ./backend/python-flask

    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
    networks:
      - my-network

networks:
  my-network:
    driver: bridge