/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StandingsImport } from './routes/standings'
import { Route as FixturesImport } from './routes/fixtures'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StandingsRoute = StandingsImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRoute,
} as any)

const FixturesRoute = FixturesImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesImport
      parentRoute: typeof rootRoute
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/standings': typeof StandingsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/standings': typeof StandingsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/standings': typeof StandingsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fixtures' | '/standings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fixtures' | '/standings'
  id: '__root__' | '/' | '/fixtures' | '/standings'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixturesRoute: typeof FixturesRoute
  StandingsRoute: typeof StandingsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixturesRoute: FixturesRoute,
  StandingsRoute: StandingsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fixtures",
        "/standings"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fixtures": {
      "filePath": "fixtures.tsx"
    },
    "/standings": {
      "filePath": "standings.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
